apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "oc-opdev-e2e.operatorframework.io.oc-opdev-e2e.operatorframework.io/v1alpha1",
          "kind": "Registry",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "registry"
            },
            "name": "registry-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-10-24T19:21:40Z"
    operators.operatorframework.io/builder: operator-sdk-v1.34.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: simple-bundle.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  description: simple-bundle
  displayName: simple-bundle
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - serviceaccounts
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - get
          - list
          - watch
        serviceAccountName: simple-bundle-sa-csv
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - registry
  links:
  - name: Registry
    url: https://registry.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.0.1
